# Generated by Django 4.0.3 on 2023-07-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfill', '0002_audiorecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='city_audio',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='person',
            name='district_audio',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='person',
            name='name_audio',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_audio',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='audiorecord',
            name='audio_file',
            field=models.FileField(upload_to='uploads/temp/'),
        ),
    ]
