# Generated by Django 4.0.3 on 2023-07-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formfill', '0003_person_city_audio_person_district_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiorecord',
            name='audio_file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
